version: "3.9"
services:
    postgres:
        image: postgres:9.6.22-alpine
        ports:
            - "5432:5432"
        environment:
            POSTGRES_HOST_AUTH_METHOD: trust
            POSTGRES_DB: aibrush
        # mount local host volume in .database/ folder
        volumes:
            - pg-data:/var/lib/postgresql
    localstack: 
        image: localstack/localstack:latest
        environment: 
        - DEFAULT_REGION=ap-northeast-2
        - EDGE_PORT=4566
        - SERVICES=sqs,logs
        ports: 
        - '4566-4583:4566-4583'
volumes:
    pg-data: {}
    # mail-data: {}
