version: "3.9"
services:
    postgres:
        image: postgres:9.6.22-alpine
        ports:
            - "5432:5432"
        environment:
            POSTGRES_HOST_AUTH_METHOD: trust
        # mount local host volume in .database/ folder
        volumes:
            - pg-data:/var/lib/postgresql
    # mailcatcher
    # mailcatcher:
    #     image: schickling/mailcatcher
    #     ports:
    #         - "1080:1080"
    #         - "1025:1025"
    #     environment:
    #         MAILCATCHER_SMTP_PORT: 1025
    #         MAILCATCHER_SMTP_AUTHENTICATION: "off"
    #         MAILCATCHER_START_SCRIPT: "true"
    #     volumes:
    #         - mail-data:/var/mail
volumes:
    pg-data: {}
    # mail-data: {}
