openapi: 3.0.0
tags:
  - name: AIBrush

info:
  title: AIBrush API
  description: Orchestration backend for AI Brush
  version: 1.0.0
  contact:
    email: wolfgangmeyers@gmail.com
servers:
  - url: https://aibrush.ngrok.io
  - url: /
paths:
  /api/images:
    get:
      description: Get a list of saved images
      operationId: listImages
      tags:
        - AIBrush
      parameters:
        - name: cursor
          in: query
          required: false
          schema:
            type: integer
        - name: limit
          in: query
          required: false
          schema:
            type: integer
        - name: direction
          in: query
          required: false
          schema:
            type: string
            enum:
              - asc
              - desc
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ImageList"
    # create image
    post:
      description: Create a new image
      operationId: createImage
      tags:
        - AIBrush
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CreateImageInput"
      responses:
        "201":
          description: Success
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Image"
  /api/images/{id}:
    get:
      description: Get a saved image by id
      operationId: getImage
      tags:
        - AIBrush
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
        - name: download
          in: query
          required: false
          schema:
            type: string
            enum: ["thumbnail", "image"]
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Image"

    # update image
    patch:
      description: Update a saved image
      operationId: updateImage
      tags:
        - AIBrush
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UpdateImageInput"
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Image"
    delete:
      description: Delete a saved image
      operationId: deleteImage
      tags:
        - AIBrush
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        "204":
          description: Success
  /api/images/{id}/image.jpg:
    get:
      description: Get the binary image data
      operationId: getImageData
      tags:
        - AIBrush
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Success
          content:
            image/jpeg:
              schema:
                type: string
                format: binary
  /api/images/{id}/thumbnail.jpg:
    get:
      description: Get the binary thumbnail data
      operationId: getThumbnailData
      tags:
        - AIBrush
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Success
          content:
            image/jpeg:
              schema:
                type: string
                format: binary
  /api/images/{id}/video.mp4:
    get:
      description: Get the binary video data
      operationId: getVideoData
      tags:
        - AIBrush
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Success
          content:
            video/mp4:
              schema:
                type: string
                format: binary
    put:
      description: Update the video data
      operationId: updateVideoData
      tags:
        - AIBrush
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      requestBody:
        content:
          video/mp4:
            schema:
              type: string
              format: binary
      responses:
        "200":
          description: Success
  /api/process-image:
    put:
      description: Get the next pending image and set its status to processing.
      operationId: processImage
      tags:
        - AIBrush
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/ProcessImageInput"
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Image"
  /api/suggestion-seeds:
    get:
      description: Get a list of suggestion seeds
      operationId: listSuggestionSeeds
      tags:
        - AIBrush
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/SuggestionSeedList"
    post:
      description: Create a new suggestion seed
      operationId: createSuggestionSeed
      tags:
        - AIBrush
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/SuggestionSeedInput"
      responses:
        "201":
          description: Success
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/SuggestionSeed"
  /api/suggestion-seeds/{id}:
    get:
      description: Get a suggestion seed by id
      operationId: getSuggestionSeed
      tags:
        - AIBrush
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/SuggestionSeed"
    patch:
      description: Update a suggestion seed
      operationId: updateSuggestionSeed
      tags:
        - AIBrush
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/SuggestionSeedInput"
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/SuggestionSeed"
    delete:
      description: Delete a suggestion seed
      operationId: deleteSuggestionSeed
      tags:
        - AIBrush
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        "204":
          description: Success
  /api/suggestions-jobs:
    get:
      description: Get a list of suggestions jobs
      operationId: listSuggestionsJobs
      tags:
        - AIBrush
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/SuggestionsJobList"
    post:
      description: Create a new suggestions job
      operationId: createSuggestionsJob
      tags:
        - AIBrush
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CreateSuggestionsJobInput"
      responses:
        "201":
          description: Success
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/SuggestionsJob"
  /api/suggestions-jobs/{id}:
    get:
      description: Get a suggestions job by id
      operationId: getSuggestionsJob
      tags:
        - AIBrush
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/SuggestionsJob"
    patch:
      description: Update a suggestions job
      operationId: updateSuggestionsJob
      tags:
        - AIBrush
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UpdateSuggestionsJobInput"
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/SuggestionsJob"
    delete:
      description: Delete a suggestions job
      operationId: deleteSuggestionsJob
      tags:
        - AIBrush
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        "204":
          description: Success
  /api/process-suggestion-job:
    post:
      description: Process a suggestions job
      operationId: processSuggestionsJob
      tags:
        - AIBrush
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/SuggestionsJob"
  # login by email
  /api/auth/login:
    post:
      description: Login by email
      operationId: login
      tags:
        - AIBrush
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/LoginInput"
      responses:
        "204":
          description: Success
  /api/auth/verify:
    post:
      description: Verify Login code
      operationId: verify
      tags:
        - AIBrush
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/VerifyLoginInput"
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/LoginResult"
        "400":
          description: Invalid code
  /api/auth/refresh:
    post:
      description: Refresh Login code
      operationId: refresh
      tags:
        - AIBrush
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/RefreshLoginInput"
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/LoginResult"
  # healthcheck
  /api/healthcheck:
    get:
      description: Healthcheck
      operationId: healthcheck
      tags:
        - AIBrush
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Healthcheck"

components:
  schemas:
    CreateImageInput:
      type: object
      properties:
        phrases:
          type: array
          items:
            type: string
        label:
          type: string
        iterations:
          type: integer
        parent:
          type: string
        encoded_image:
          type: string
        enable_video:
          type: boolean
        enable_zoom:
          type: boolean
        zoom_frequency:
          type: integer
        zoom_scale:
          type: number
        zoom_shift_x:
          type: number
        zoom_shift_y:
          type: number

    UpdateImageInput:
      type: object
      properties:
        label:
          type: string
        current_iterations:
          type: integer
        phrases:
          type: array
          items:
            type: string
        status:
          type: string
          enum: [pending, processing, completed, saved]
        encoded_image:
          type: string

    Image:
      properties:
        id:
          type: string
        created_at:
          type: integer
        created_by:
          type: string
        updated_at:
          type: integer
        phrases:
          type: array
          items:
            type: string
        label:
          type: string
        parent:
          type: string
        iterations:
          type: integer
        current_iterations:
          type: integer
        score:
          type: integer
        status:
          type: string
          enum: [pending, processing, completed, saved]
        enable_video:
          type: boolean
        enable_zoom:
          type: boolean
        zoom_frequency:
          type: integer
        zoom_scale:
          type: number
        zoom_shift_x:
          type: number
        zoom_shift_y:
          type: number
      required:
        - id
        - created_at
        - created_by
        - updated_at
        - phrases
        - label
        - parent
        - iterations
        - current_iterations
        - score
        - status
        - enable_video
    ImageList:
      properties:
        images:
          type: array
          items:
            $ref: "#/components/schemas/Image"
    ProcessImageInput:
      properties:
        zoom_supported:
          type: boolean
      required:
        - zoom_supported
    LoginInput:
      type: object
      properties:
        email:
          type: string
    VerifyLoginInput:
      type: object
      properties:
        email:
          type: string
        code:
          type: string
    RefreshLoginInput:
      type: object
      properties:
        refreshToken:
          type: string
      required:
        - refresh_token
    LoginResult:
      type: object
      properties:
        accessToken:
          type: string
        refreshToken:
          type: string
    SuggestionSeed:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        description:
          type: string
        items:
          type: array
          items:
            type: string
        created_by:
          type: string
      required:
        - id
        - name
        - description
        - items
        - created_by
    SuggestionSeedList:
      properties:
        suggestionSeeds:
          type: array
          items:
            $ref: "#/components/schemas/SuggestionSeed"
      required:
        - suggestionSeeds
    SuggestionSeedInput:
      type: object
      properties:
        name:
          type: string
        description:
          type: string
        items:
          type: array
          items:
            type: string
      required:
        - name
        - items
    SuggestionsJob:
      type: object
      properties:
        id:
          type: string
        created_by:
          type: string
        created_at:
          type: integer
        updated_at:
          type: integer
        seed_id:
          type: string
        status:
          type: string
          enum: [pending, processing, completed, saved]
        result:
          type: array
          items:
            type: string
      required:
        - id
        - created_by
        - created_at
        - updated_at
        - seed_id
        - status
        - result
    SuggestionsJobList:
      properties:
        suggestionsJobs:
          type: array
          items:
            $ref: "#/components/schemas/SuggestionsJob"
    CreateSuggestionsJobInput:
      type: object
      properties:
        seed_id:
          type: string
    UpdateSuggestionsJobInput:
      type: object
      properties:
        status:
          type: string
          enum: [pending, processing, completed, saved]
        result:
          type: array
          items:
            type: string



    Healthcheck:
      type: object
      properties:
        status:
          type: string
          enum: [ok]

